/**
 * CityTier Model — admin-controlled city-to-logistics-tier assignments.
 *
 * Each document maps one city to a tier (1/2/3) and a default shipping provider.
 * On create/update the CityTierService automatically upserts a ShippingRule
 * (source: "city_tier") at priority 100–166 so the factory picks it up
 * without any factory code changes.
 *
 * autoRuleId tracks the managed rule — delete is cascaded to the rule inside a
 * MongoDB transaction via withTransaction().
 */

import mongoose from "mongoose";

const cityTierSchema = new mongoose.Schema(
  {
    /** City name as entered by admin — stored as-entered, queried case-insensitively */
    city: {
      type: String,
      required: true,
      trim: true,
    },

    /** Logistics tier: 1 = metro, 2 = state capital / large city, 3 = semi-urban / rural */
    tier: {
      type: Number,
      required: true,
      enum: [1, 2, 3],
    },

    /** The shipping provider routed to for this city */
    defaultProvider: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ShippingProvider",
      required: true,
    },

    /**
     * The ShippingRule auto-generated by this tier entry.
     * Null until first rule upsert succeeds (set inside the create transaction).
     * When this entry is deleted, this rule is also deleted (in the same transaction).
     */
    autoRuleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ShippingRule",
      default: null,
    },

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

// Case-insensitive unique index on city name
cityTierSchema.index(
  { city: 1 },
  { unique: true, collation: { locale: "en", strength: 2 } }
);

cityTierSchema.index({ tier: 1 });
cityTierSchema.index({ defaultProvider: 1 });

const CityTier = mongoose.model("CityTier", cityTierSchema);

export default CityTier;
