/**
 * ShippingRule Model — condition-based provider routing rules.
 *
 * Rules determine which provider handles a shipment based on:
 * pincode, weight, payment mode, state, order value, etc.
 *
 * The ProviderFactory evaluates rules in priority order to
 * find the best-matching provider for a given shipment context.
 */

import mongoose from "mongoose";

const shippingRuleSchema = new mongoose.Schema(
  {
    /** Reference to the ShippingProvider this rule routes to */
    providerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ShippingProvider",
      required: true,
      index: true,
    },

    /** Human-readable rule name for dashboard display */
    ruleName: {
      type: String,
      required: true,
      trim: true,
    },

    /** Conditions that must ALL match for this rule to apply */
    conditions: {
      /** Destination pincodes (exact or prefix match) */
      pincodes: {
        type: [String],
        default: [],
      },

      /** Origin pincodes (warehouse / pickup location) */
      originPincodes: {
        type: [String],
        default: [],
      },

      /** Minimum weight in grams */
      minWeight: {
        type: Number,
        default: 0,
      },

      /** Maximum weight in grams */
      maxWeight: {
        type: Number,
        default: Infinity,
      },

      /** Applicable payment modes */
      paymentModes: {
        type: [String],
        enum: ["COD", "PREPAID"],
        default: [],
      },

      /** Applicable states */
      states: {
        type: [String],
        default: [],
      },

      /** Maximum order value */
      maxValue: {
        type: Number,
        default: Infinity,
      },

      /** Minimum order value */
      minValue: {
        type: Number,
        default: 0,
      },
    },

    /** Whether this rule is currently active */
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },

    /** Evaluation priority — lower = checked first */
    priority: {
      type: Number,
      default: 10,
    },

    /**
     * Origin of this rule.
     * "manual"    — created by admin directly via the rule management API
     * "city_tier" — auto-generated by the CityTier manager; edit via tier API only
     */
    source: {
      type: String,
      enum: ["manual", "city_tier"],
      default: "manual",
    },
  },
  {
    timestamps: true,
  }
);

/* ── Index for efficient rule evaluation ────────────────────────────────── */

shippingRuleSchema.index({ isActive: 1, priority: 1, providerId: 1 });

const ShippingRule = mongoose.model("ShippingRule", shippingRuleSchema);

export default ShippingRule;
